language: go
sudo: required

services:
  - docker
 
before_install:
  - docker build -t v2raylrli.heroku.com/"$HEROKU_APPNAME"/web .
  - docker login -u "$HEROKU_EMAIL" -p "$HEROKU_APIKEY" v2raylrli.heroku.com
  - docker push v2raylrli.heroku.com/"$HEROKU_APPNAME"/web
